server:
  port: 1111
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate.ddl-auto: none
    open-in-view: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    continue-on-error: true
    initialization-mode: embedded
#    url: jdbc:mariadb://bfjrxdpxrza9qllq.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/bmivm5jebb9pwpk1
#    username: yfwr2wtujh9u4kid
#    password: y3xzju0me4k7ylab
    url: jdbc:mariadb://localhost:3306/hobohunt
    username: root
    password: 